language: php

php:
  - 5.5
  - 5.6
  - '7.0'
  - hhvm

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  # temp hack for PHPSPEC to work with PHP 7:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then wget https://github.com/digitalkaoz/typehint-to-docblock/releases/download/0.2.2/typehint-to-docblock.phar && php typehint-to-docblock.phar transform tests/spec; fi;'

script:
  - vendor/bin/phpspec run --verbose
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN

branches:
  except:
    - php53
